function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 12-Sep-2016
%----------------------------------------------------


% Threshold image - global threshold
BW = imbinarize(X);

% Threshold image - manual threshold
BW = X > 40;

% Invert mask
BW = imcomplement(BW);

% Dilate mask with square
width = 10;
se = strel('square', width);
BW = imdilate(BW, se);

% Clear borders
BW = imclearborder(BW);

% Erode mask with square
width = 8;
se = strel('square', width);
BW = imerode(BW, se);

% Erode mask with square
width = 8;
se = strel('square', width);
BW = imerode(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;